##The website title
name: Kod Defteri
timezone: Europe/Istanbul
future: true
markdown: kramdown
##syntax highlighter. change it to pygments
highlighter: rouge

##define base_url for valid usage in sitemap.xml and robots.txt
base_url: http://incemehm.github.io
sass:
  sass_dir: _sass
  style: :compressed
paginate: 5
paginate_path: "Sayfa-:num"
##The website description (to be used in meta tags)
description: Put website description for your home page. (about 50 words or more)
##Some frequently used keywords on your website
keywords: some, relevant, keywords, for, usage, in metatags
tag_page: /tags

##define this for disqus comment support
disqus: incemehm

##set this to enable google analytics
#ga_id: analyticsID
#ga_domain: analyticsDomain

##Some commonly used links
links:
  facebook: incemehm
  twitter: incemehm
  linkedin: incemehm
  email: mehmetince2212@gmail.com
  github: incemehm
  stackoverflow: 1439935

##put desired image in img/ directory and set the value accordingly. If not defined, a placeholder image will be used.
about_image: profile.png
##comment this if you want full width posts with no sidebar
sidebar: on
plugins: [jekyll-paginate]

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
